version: '3.8'
services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - APP_USER=app
      - APP_PASSWORD=secret
      - APP_DB=newsletter
    ports:
      - "5432:5432"
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/01-init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5

configs:
  init_sql:
    content: |
      #!/bin/bash
      set -e
      echo "Creating app user..."
      psql -v ON_ERROR_STOP=1 --username "$${POSTGRES_USER}" --dbname "$${POSTGRES_DB}" <<-EOSQL
        CREATE USER $${APP_USER} WITH PASSWORD '$${APP_PASSWORD}';
        ALTER USER $${APP_USER} CREATEDB;
      EOSQL