version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${SUPERUSER:-postgres}
      POSTGRES_PASSWORD: ${SUPERUSER_PWD:-password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command: ["postgres", "-N", "1000"] # Increase max connections
